#
#  project structure
#
directory: site
artifacts:
  - prez
  - posts
  - assets
layout: layout.rhtml
tailwind: site.css

#
#  site configuration
#
title: mike.daless.io
css:
  - assets/solarized-dark.css
navigation:
  - name: mike.daless.io
    file: index.html
  - name: Speaking
    file: media.html
  - name: Writing
    file: posts.html
  - name: Projects
    file: projects.html
  - name: Resum√©
    file: resume.html
files:
  - 404.html
  - feed.xml
  - posts/2015/12/abstraction-or-the-gift-of-our-weak-brains.html
  - posts/2025/03/open-source-update.html
  - posts/2025/04/open-source-update.html
  - posts/2025/09/universal-rubygem-precompilation.html
  - posts/2026/01/open-source-update.html
redirects:
  - from: "/about.html"
    to: "/"
  - from: "/prez.html"
    to: "/media.html"
  - from: "/Michael-Dalessio.html"
    to: "/resume.html"
